#!/bin/bash

source server-config

echo "Zatrzymanie serwera klepak..."
systemctl stop klepak

tar --exclude="$TARGET_DIR/.venv" -czfv $BACKUP_DIR/klepak_$(date +%Y%m%d_%H%M%S).tgz -C $BACKUP_WORK_DIR klepak
echo "Backup utworzony: /srv/backup/klepak_mini_$(date +%Y%m%d_%H%M%S).tgz"

echo "Usuwanie plików i folderów z katalogu $TARGET_DIR, z wyjątkami..."
mkdir /tmp/empty_dir
rsync -a --delete \
    --exclude='/.venv' \
    --exclude='/server-reinstall' \
    --exclude='/logs' \
    --exclude='/data' \
    --exclude='/static' \
    --exclude='/static/photos' \
    /tmp/empty_dir/ "$TARGET_DIR/"
rm -f -r /tmp/empty_dir

echo "Klonowanie repozytorium z $REPO_URL do katalogu $REPO_DIR..."
git clone "$REPO_URL" "$REPO_DIR"

echo "Przenoszenie plików z katalogu $REPO_DIR do katalogu $TARGET_DIR..."
rm -f -d -r "$REPO_DIR/.git"
rm -f -d -r "$REPO_DIR/.vscode"
rm -f -d -r "$REPO_DIR/data"
rm -f -d -r "$REPO_DIR/logs"
rm "$REPO_DIR/.gitignore"
rm "$REPO_DIR/server-reinstall"
mv "$REPO_DIR"/* "$TARGET_DIR/"

echo "Usuwanie pustego katalogu $REPO_DIR..."
rm -f -d -r "$REPO_DIR"

echo "Ustawienie uprawnień do plików..."
chown -R dobrowit:dobrowit "$TARGET_DIR"
chmod +x $TARGET_DIR/server-*

echo "Operacje zakończone pomyślnie."

echo "Uruchamianie serwera klepak..."
systemctl start klepak

echo -e "Aktualizacja serwera Klepak ukończona - `date +"%Y-%m-%d %H:%M:%S"`.\n\n\
Sprawdź czy coś się nie popsuło:\n\n\
http://maluch3.mikr.us:20162/status\n\n\
https://klepak.cytr.us:20162/status" | pusher
