#!/bin/bash

apt update
apt upgrade -y
apt install calc python3-venv python3 pip -y

python3 -m venv .venv
source ./.venv/bin/activate
pip install -r requirements.txt

cp klepak.service /etc/systemd/system/klepak.service
systemctl daemon-reload
systemctl enable klepak.service
