#!/bin/bash

TARGET_DIR="/srv/klepak"
REPO_DIR="$TARGET_DIR/Klepak"
REPO_URL="https://github.com/Dobrowit/Klepak/"
EXCLUDE_FILE="$TARGET_DIR/server-reinstall"
EXCLUDE_DIR="$TARGET_DIR/data"

echo "Zatrzymanie serwera klepak..."
systemctl stop klepak

echo "Usuwanie plików i folderów z katalogu $TARGET_DIR, z wyjątkiem $EXCLUDE_FILE..."
find "$TARGET_DIR" -mindepth 1 \
    -not -path "$EXCLUDE_FILE" \
    -not -path "$EXCLUDE_DIR" \
    -not -path "$EXCLUDE_DIR/*" \
    -exec rm -rf {} +

echo "Klonowanie repozytorium z $REPO_URL do katalogu $REPO_DIR..."
git clone "$REPO_URL" "$REPO_DIR"

echo "Przenoszenie plików z katalogu $REPO_DIR do katalogu $TARGET_DIR..."
rm -f -d -r "$REPO_DIR/.git"
rm -f -d -r "$REPO_DIR/.vscode"
rm -f -d -r "$REPO_DIR/data"
rm "$REPO_DIR/.gitignore"
rm "$REPO_DIR/server-reinstall"
mv "$REPO_DIR"/* "$TARGET_DIR/"

echo "Usuwanie pustego katalogu $REPO_DIR..."
rm -f -d -r "$REPO_DIR"

echo "Pobieranie bibliotek..."
cd "$TARGET_DIR"
python3 -m venv .venv
source "$TARGET_DIR/.venv/bin/activate"
pip install -r requirements.txt

echo "Ustawienie uprawnień do plików..."
chown -R dobrowit:dobrowit "$TARGET_DIR"
chmod +x "$TARGET_DIR/server-start"
chmod +x "$TARGET_DIR/server-setup"

echo "Operacje zakończone pomyślnie."

echo "Uruchamianie serwera klepak..."
systemctl start klepak
