#!/bin/bash

TARGET_DIR="/srv/klepak"
REPO_DIR="$TARGET_DIR/Klepak"
REPO_URL="https://github.com/Dobrowit/Klepak/"

echo "Zatrzymanie serwera klepak..."
systemctl stop klepak

echo "Usuwanie plików i folderów z katalogu $TARGET_DIR, z wyjątkami..."
find "$TARGET_DIR" -mindepth 1 \
    -not -path "$TARGET_DIR/server-reinstall" \
    -not -path "$TARGET_DIR/logs" \
    -not -path "$TARGET_DIR/logs/*" \
    -not -path "$TARGET_DIR/data" \
    -not -path "$TARGET_DIR/data/*" \
    -not -path "$TARGET_DIR/.venv" \
    -not -path "$TARGET_DIR/.venv/*" \
    -not -path "$TARGET_DIR/static/photos" \
    -not -path "$TARGET_DIR/static/photos/*" \
    -exec rm -rf {} +

echo "Klonowanie repozytorium z $REPO_URL do katalogu $REPO_DIR..."
git clone "$REPO_URL" "$REPO_DIR"

echo "Przenoszenie plików z katalogu $REPO_DIR do katalogu $TARGET_DIR..."
rm -f -d -r "$REPO_DIR/.git"
rm -f -d -r "$REPO_DIR/.vscode"
rm -f -d -r "$REPO_DIR/data"
rm -f -d -r "$REPO_DIR/logs"
rm "$REPO_DIR/.gitignore"
rm "$REPO_DIR/server-reinstall"
mv "$REPO_DIR"/* "$TARGET_DIR/"

echo "Usuwanie pustego katalogu $REPO_DIR..."
rm -f -d -r "$REPO_DIR"

echo "Ustawienie uprawnień do plików..."
chown -R dobrowit:dobrowit "$TARGET_DIR"
chmod +x "$TARGET_DIR/server-start"
chmod +x "$TARGET_DIR/server-setup"

echo "Operacje zakończone pomyślnie."

echo "Uruchamianie serwera klepak..."
systemctl start klepak

echo -e "Aktualizacja serwera Klepak ukończona - `date +"%Y-%m-%d %H:%M:%S"`.\n\n\
Sprawdź czy coś się nie popsuło:\n\n\
http://maluch3.mikr.us:20162/status\n\n\
https://klepak.cytr.us:20162/status" | pusher