#!/bin/bash

source server-config

tar -czf $BACKUP_DIR/klepak_r_$(date +%Y%m%d_%H%M%S).tgz -C $BACKUP_WORK_DIR klepak
KOM="Backup utworzony: /srv/backup/klepak_r_$(date +%Y%m%d_%H%M%S).tgz"
echo $KOM
echo $KOM | pusher
