#!/bin/bash

TARGET_DIR="/srv/klepak"
BACKUP_WORK_DIR="/srv"
BACKUP_DIR="$BACKUP_WORK_DIR/backup"
REPO_DIR="$TARGET_DIR/Klepak"
REPO_URL="https://github.com/Dobrowit/Klepak/"

echo "Zatrzymanie serwera klepak..."
systemctl stop klepak

tar -czf $BACKUP_DIR/klepak_r_$(date +%Y%m%d_%H%M%S).tgz -C $BACKUP_WORK_DIR klepak
echo "Backup utworzony: /srv/backup/klepak_r_$(date +%Y%m%d_%H%M%S).tgz"

echo "Usuwanie plików i folderów z katalogu $TARGET_DIR, z wyjątkami..."
mkdir /tmp/empty_dir
rsync -a --delete \
    --exclude='/server-reinstall' \
    --exclude='/logs' \
    --exclude='/data' \
    --exclude='/static' \
    --exclude='/static/photos' \
    /tmp/empty_dir/ "$TARGET_DIR/"
rm -f -r /tmp/empty_dir

echo "Klonowanie repozytorium z $REPO_URL do katalogu $REPO_DIR..."
git clone "$REPO_URL" "$REPO_DIR"

echo "Przenoszenie plików z katalogu $REPO_DIR do katalogu $TARGET_DIR..."
rm -f -d -r "$REPO_DIR/.git"
rm -f -d -r "$REPO_DIR/.vscode"
rm -f -d -r "$REPO_DIR/data"
rm -f -d -r "$REPO_DIR/logs"
rm "$REPO_DIR/.gitignore"
rm "$REPO_DIR/server-reinstall"
mv "$REPO_DIR"/* "$TARGET_DIR/"

echo "Usuwanie pustego katalogu $REPO_DIR..."
rm -f -d -r "$REPO_DIR"

echo "Pobieranie bibliotek..."
cd "$TARGET_DIR"
python3 -m venv .venv
source "$TARGET_DIR/.venv/bin/activate"
pip install -r requirements.txt

echo "Ustawienie uprawnień do plików..."
chown -R dobrowit:dobrowit "$TARGET_DIR"
chmod +x "$TARGET_DIR/server-start"
chmod +x "$TARGET_DIR/server-setup"
chmod +x "$TARGET_DIR/server-update"

echo "Operacje zakończone pomyślnie."

echo "Uruchamianie serwera klepak..."
systemctl start klepak

echo -e "Reinstalacja serwera Klepak ukończona - `date +"%Y-%m-%d %H:%M:%S"`.\n\n\
Sprawdź czy coś się nie popsuło:\n\n\
http://maluch3.mikr.us:20162/status\n\n\
https://klepak.cytr.us:20162/status" | pusher