#!/bin/bash

# Sprawdzenie dystrybucji Linux
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    echo "Nie można zidentyfikować systemu operacyjnego."
    exit 1
fi

# Wykonanie poleceń w zależności od systemu
case "$OS" in
    ubuntu|debian)
        echo "System to Ubuntu lub Debian"
        # Wykonaj polecenia dla Ubuntu/Debian
        apt update
        apt upgrade -y
        apt install calc python3-venv python3 pip -y
        cp klepak.service /etc/systemd/system/klepak.service
        systemctl daemon-reload
        systemctl enable klepak.service
        ;;
    alpine)
        echo "System to Alpine Linux"
        # Wykonaj polecenia dla Alpine Linux
        apk update
        apk upgrade
        apk add mc htop ncdu python3 python-setuptools python3-dev
        cp openrc-klepak /etc/init.d/klepak
        rc-update add klepak default
        rc-service klepak start
        rc-update add klepak default
        rc-service klepak status
        ;;
    *)
        echo "Niewspierana dystrybucja: $OS"
        exit 1
        ;;
esac

python3 -m venv .venv
source ./.venv/bin/activate
pip install -r requirements.txt
