- zmiana struktury categories.json (kategorie i podkategorie)
- rozdzielenie endpointów z API pod /api/
- implementacja kalendarza iCAL/JSON (imprezy, śmieci)
- wysyłanie komunikatów
- @app.route('/', methods=['GET','POS']) if request.method == 'GET':
- sprawdzić skrypty instalacyjne na Ubuntu, Debian i Alpine